const CITY_GEOHASH_MAP = {
  'Marseille': 'spey64vxu2hg',
  'Paris': 'u09tvw0z7',
  'Lyon': 'u0j1h2b3c',
  'Toulouse': 'spq3k4m5n',
  'Nice': 'spn2j3k4l',
  'Nantes': 'gbsuv8xyz',
  'Strasbourg': 'u0j8k9l0m',
  'Montpellier': 'spn5m6n7o',
  'Bordeaux': 'spq6n7o8p',
  'Lille': 'u0k2l3m4n',
  'Rennes': 'gbsw1x2y3',
  'Reims': 'u09y0z1a2',
  'Le Havre': 'u0k5l6m7n',
  'Saint-Étienne': 'u0j2k3l4m',
  'Toulon': 'spn8m9n0o',
  'Angers': 'gbsx4y5z6',
  'Grenoble': 'u0j5k6l7m',
  'Dijon': 'u0j9k0l1m',
  'Nîmes': 'spn9m0n1o',
  'Villeurbanne': 'u0j1h2b3c',
  'Saint-Denis': 'u09tvw0z7',
  'Le Mans': 'gbsx7y8z9',
  'Aix-en-Provence': 'spey64vxu2hg',
  'Clermont-Ferrand': 'u0j3k4l5m',
  'Brest': 'gbsy0z1a2',
  'Limoges': 'spq9n0o1p',
  'Tours': 'gbsy3z4a5',
  'Amiens': 'u0k8l9m0n',
  'Perpignan': 'spn0m1n2o',
  'Metz': 'u0j6k7l8m',
  'Besançon': 'u0j0k1l2m',
  'Boulogne-Billancourt': 'u09tvw0z7',
  'Orléans': 'u09y3z4a5',
  'Mulhouse': 'u0j7k8l9m',
  'Rouen': 'u0k9l0m1n',
  'Caen': 'u0k3l4m5n',
  'Nancy': 'u0j4k5l6m',
  'Argenteuil': 'u09tvw0z7',
  'Montreuil': 'u09tvw0z7',
  'Roubaix': 'u0k2l3m4n',
  'Tourcoing': 'u0k2l3m4n',
  'Nanterre': 'u09tvw0z7',
  'Avignon': 'spn3m4n5o',
  'Créteil': 'u09tvw0z7',
  'Dunkirk': 'u0k6l7m8n',
  'Poitiers': 'gbsy6z7a8'
};

const CITY_NEIGHBORHOOD_MAP = {
  'Marseille': 'marseille-pointe-rouge',
  'Paris': 'paris-centre',
  'Lyon': 'lyon-centre',
  'Toulouse': 'toulouse-centre',
  'Nice': 'nice-centre',
  'Nantes': 'nantes-centre',
  'Strasbourg': 'strasbourg-centre',
  'Montpellier': 'montpellier-centre',
  'Bordeaux': 'bordeaux-centre',
  'Lille': 'lille-centre',
  'Rennes': 'rennes-centre',
  'Reims': 'reims-centre',
  'Le Havre': 'le-havre-centre',
  'Saint-Étienne': 'saint-etienne-centre',
  'Toulon': 'toulon-centre',
  'Angers': 'angers-centre',
  'Grenoble': 'grenoble-centre',
  'Dijon': 'dijon-centre',
  'Nîmes': 'nimes-centre',
  'Villeurbanne': 'villeurbanne-centre',
  'Saint-Denis': 'saint-denis-centre',
  'Le Mans': 'le-mans-centre',
  'Aix-en-Provence': 'aix-en-provence-centre',
  'Clermont-Ferrand': 'clermont-ferrand-centre',
  'Brest': 'brest-centre',
  'Limoges': 'limoges-centre',
  'Tours': 'tours-centre',
  'Amiens': 'amiens-centre',
  'Perpignan': 'perpignan-centre',
  'Metz': 'metz-centre',
  'Besançon': 'besancon-centre',
  'Boulogne-Billancourt': 'boulogne-billancourt-centre',
  'Orléans': 'orleans-centre',
  'Mulhouse': 'mulhouse-centre',
  'Rouen': 'rouen-centre',
  'Caen': 'caen-centre',
  'Nancy': 'nancy-centre',
  'Argenteuil': 'argenteuil-centre',
  'Montreuil': 'montreuil-centre',
  'Roubaix': 'roubaix-centre',
  'Tourcoing': 'tourcoing-centre',
  'Nanterre': 'nanterre-centre',
  'Avignon': 'avignon-centre',
  'Créteil': 'creteil-centre',
  'Dunkirk': 'dunkerque-centre',
  'Poitiers': 'poitiers-centre'
};

function getGeohashForCity(city) {
  return CITY_GEOHASH_MAP[city] || 'spey64vxu2hg';
}

function getNeighborhoodForCity(city) {
  return CITY_NEIGHBORHOOD_MAP[city] || city.toLowerCase().replace(/\s+/g, '-');
}

module.exports = {
  CITY_GEOHASH_MAP,
  CITY_NEIGHBORHOOD_MAP,
  getGeohashForCity,
  getNeighborhoodForCity
};
